In [1]:
%load_ext nb_black
%load_ext lab_black

<IPython.core.display.Javascript object>

In [24]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

<IPython.core.display.Javascript object>

In [28]:
dataset = pd.read_csv(
    "Data.csv"
)  # pd.read_csv() is used to import the dataset from csv format to a pandas dataset.
X = dataset.iloc[
    :, :-1
].values  # iloc is used to get the specified sub-dataset from a given dataset. dataset.iloc(range of rows, range of columns)
Y = dataset.iloc[:, -1].values  # dataset.values changes a pandas dataset into a matrix.

<IPython.core.display.Javascript object>

In [30]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


<IPython.core.display.Javascript object>

In [31]:
print(Y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


<IPython.core.display.Javascript object>

In [32]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(
    missing_values=np.nan, strategy="mean"
)  # Imputer is used to fill the gaps in data by using 'mean' or 'min' in place of a missing value.
imputer.fit(
    X[:, 1:3]
)  # fit is used to find the value that replaces the NaN datapoint in the matrix.
X[:, 1:3] = imputer.transform(
    X[:, 1:3]
)  # transform is used to replace the NaN datapoint with the one calculated in the above step.

<IPython.core.display.Javascript object>

In [33]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


<IPython.core.display.Javascript object>

In [46]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(
    transformers=[("encoder", OneHotEncoder(), [0])], remainder="passthrough"
)  # encoder is used to change a categoriacal variable into a numerical variable. 
   # It adds same number of columns to the dataset as there are categories and used different combinations of 1's and 0's in these columns to represent a variable.
X = np.array(ct.fit_transform(X))

<IPython.core.display.Javascript object>

In [35]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


<IPython.core.display.Javascript object>

In [47]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
Y = le.fit_transform(
    Y
)  # label encoder is used to change a categorical binary variable into 0's and 1's, though not recommended it can also be used for non-binary variables

<IPython.core.display.Javascript object>

In [37]:
print(Y)

[0 1 0 0 1 1 0 1 0 1]


<IPython.core.display.Javascript object>

In [48]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size=0.2, random_state=1
)  # train_test_split is used to split the given datasets into training and testing dataset of given sizes.

<IPython.core.display.Javascript object>

In [39]:
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


<IPython.core.display.Javascript object>

In [40]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


<IPython.core.display.Javascript object>

In [17]:
print(Y_train)

[0 1 0 0 1 1 0 1]


<IPython.core.display.Javascript object>

In [41]:
print(Y_test)

[0 1]


<IPython.core.display.Javascript object>

In [49]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(
    X_train[:, 3:]
)  # Feature scaling is used to get all the numerical variables into same range so that it takes less time to train the model.
# Standard Scaling makes the range (-3, 3)
# Normalized Scaling makes the range (0, 1)
X_test[:, 3:] = sc.transform(X_test[:, 3:])

<IPython.core.display.Javascript object>

In [43]:
print(X_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


<IPython.core.display.Javascript object>

In [44]:
print(X_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]


<IPython.core.display.Javascript object>